version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    cooldown:
      default-days: 7
    schedule:
      interval: 'daily'
    groups:
      alpinejs:
        patterns:
          - alpinejs
          - '@types/alpinejs'
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
      tailwindcss:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      typescript-eslint:
        patterns:
          - 'typescript-eslint'
          - '@typescript-eslint/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    cooldown:
      default-days: 7
    schedule:
      interval: 'daily'
